### ISSUE TITLE
Integrate REST API specs (OpenAPI/Swagger)

### ISSUE THREAD

**Issue by tumidi** [questionpy-org/questionpy-docs#3]
Plugin candidates:
- https://www.neoteroi.dev/mkdocs-plugins/web/oad/
- https://github.com/bharel/mkdocs-render-swagger-plugin
- https://github.com/blueswen/mkdocs-swagger-ui-tag
- https://github.com/vrerv/mkdocs-openapi-markdown-plugin

**Comment by tumidi** [comment]
Habe verschiedene der Plugins ausprobiert, wobei `Neoteroi/mkdocs-plugins` noch das vielversprechendste ist.
Leider haben die Plugins alle irgendwelche Fehler bzw. Probleme OpenAPI-Dateien zu verarbeiten, die sich gegenseitig verlinken:

```yaml
# qppe-lms.yaml
  /package/{package_hash}:
    parameters:
      - $ref: 'qppe-server.yaml#/components/parameters/PackageHash'
```
